api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Challenge HTTP
certificatesResolvers:
  myresolver:
    acme:
      email: josemanuelitoeden@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

# Dashboard router
http:
  routers:
    traefik:
      rule: Host(`dashboard.joeden.site`) 
      entryPoints:
        - websecure
      service: api@internal
      # middlewares:                       # DO NOT DO IN PRODUCTION
      #   - auth                           # Disables the authentication        