api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false

# enable Access logs
accessLog: {}
#Configuring Multiple Filters
# accessLog:
#   filters:    
#     statusCodes:
#       - "404"
#     retryAttempts: true
#     minDuration: "10ms"

log:                  # DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
  level: INFO     

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
