version: "3"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80" # web requests
      - "8080:8080" # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
