api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Challenge TLS
certificatesResolvers:
  myresolver:
    acme:
      email: josemanuelitoeden@gmail.com  
      storage: acme.json
      tlsChallenge: true
        # # used during the challenge
        # entryPoint: web
