api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"   

# Challenge TLS
certificatesResolvers:
  myresolver:
    acme:
      email: josemanuelitoeden@gmail.com  
      storage: acme.json
      tlsChallenge: true
        # # used during the challenge
        # entryPoint: web

# Dashboard router
http:
  routers:
    traefik:
      rule: Host(`dashboard.joeden.site`)  # or use your domain + a subdomain
      entryPoints:
        - traefik
      service: api@internal
      # middlewares:                       # DO NOT DO IN PRODUCTION
      #   - auth                           # Disables the authentication